name:                noita
version:             0.1.0.0
github:              "awpr/noita-salaus"
license:             Apache-2.0
author:              "Andrew Pritchard <awpritchard@gmail.com>"
maintainer:          "Andrew Pritchard <awpritchard@gmail.com>"
copyright:           "2022 Andrew Pritchard"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/awpr/noita-salaus#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- portray
- portray-prettyprinter
- random
- JuicyPixels
- vector
- process
- random-shuffle
- rle
- fin-int
- text
- short-vec
- keyed-containers
- attenuation
- Chart
- Chart-diagrams
- data-default

library:
  source-dirs: src
